POST https://music-app-backend-aijn.onrender.com/api/auth/register
Content-Type: application/json

{
  "username": "test",
  "email": "test2@gmail.com",
  "password": "123456"
}


### Login
POST https://music-app-backend-aijn.onrender.com/api/auth/login
Content-Type: application/json

{
  "email": "vu@gmail.com",
  "password": "123456"
}

######
#### Token #### eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2dUBnbWFpbC5jb20iLCJpYXQiOjE3NjMzOTA4MDYsImV4cCI6MTc2Mzk5NTYwNn0.YrQQt8CVXb4mlDHS-HiRRBDd12UfuQPB0ROqRxxIol0
####################################
### Upload song (localhost)
### 🟢 Test Upload Song (image + audio)
### 🟢 Test Upload Song (image + audio)


################################

POST https://music-app-backend-aijn.onrender.com/api/songs/upload
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ2dUBnbWFpbC5jb20iLCJpYXQiOjE3NjM2OTU5NTMsImV4cCI6MTc2NDMwMDc1M30.TiR8yYiIvlf8U5BW1PV7XUQb-jBH5p7Py7O3TUHn0Q4
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="title"

Faded
--MyBoundary
Content-Disposition: form-data; name="artist"

Alan Walker
--MyBoundary
Content-Disposition: form-data; name="album"

Different World
--MyBoundary
Content-Disposition: form-data; name="image"; filename="cover.jpg"
Content-Type: image/jpeg

< ./test-files/cover.jpg
--MyBoundary
Content-Disposition: form-data; name="audio"; filename="song.mp3"
Content-Type: audio/mpeg

< ./test-files/song.mp3
--MyBoundary--
###
POST /api/auth/login


#####
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "123456"
}
